# Generated by Django 4.0 on 2024-03-28 18:11

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_change', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_send', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_remove', models.DateTimeField(blank=True, null=True)),
                ('data_delivery', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('chart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.chart')),
            ],
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reading', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.userproxy')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordChangeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_password_changed', models.DateTimeField(auto_now=True, null=True)),
                ('change_type', models.CharField(choices=[('created', 'Пароль создан'), ('changed', 'Пароль изменен')], default='created', editable=False, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_date', to='app_database.userproxy')),
            ],
            options={
                'verbose_name': 'Дата пароля',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(choices=[('CM', 'Community'), ('MF', 'My Files'), ('BP', 'Best Practices')], max_length=10)),
                ('type_id', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('Excel', 'Excel'), ('PDF', 'PDF')], max_length=10)),
                ('data_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_change', models.DateTimeField(blank=True, null=True)),
                ('data_delete', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('link', models.FileField(upload_to='files/')),
                ('publish', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.userproxy')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('theme', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.userproxy')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_change', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.userproxy')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.file'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.userproxy'),
        ),
        migrations.AddField(
            model_name='chart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.userproxy'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type_id', models.CharField(choices=[('READER', 'READER'), ('OWNER', 'OWNER'), ('COMMENTATOR', 'COMMENTATOR'), ('EDITOR', 'EDITOR')], max_length=20, verbose_name='Access type')),
                ('data_access_open', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_access_close', models.DateTimeField(blank=True, null=True)),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.file')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.userproxy')),
            ],
        ),
    ]
