# Generated by Django 4.0 on 2024-03-17 12:39

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_typy', models.CharField(choices=[('READER', 'READER'), ('OWNER', 'OWNER'), ('COMMENTATOR', 'COMMENTATOR'), ('EDITOR', 'EDITOR')], max_length=20, unique=True, verbose_name='Access type')),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('Excel', 'Excel'), ('PDF', 'PDF'), ('OTHER', '····')], default='OTHER', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(choices=[('CM', 'Community'), ('MF', 'My Files'), ('BP', 'Best Practices')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordChangeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_password_changed', models.DateTimeField(auto_now=True, null=True)),
                ('change_type', models.CharField(choices=[('created', 'Пароль создан'), ('changed', 'Пароль изменен')], default='created', editable=False, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_database.userproxy')),
            ],
            options={
                'verbose_name': 'Дата пароля',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_change', models.DateTimeField()),
                ('data_delete', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('publish', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.place')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.filetype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.userproxy')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_access_open', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_access_close', models.DateTimeField(blank=True, null=True)),
                ('access_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.accesstype')),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.files')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
