# Generated by Django 4.0 on 2024-03-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
