# Generated by Django 4.0 on 2024-03-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='access_type_id',
            field=models.CharField(choices=[('READER', 'READER'), ('OWNER', 'OWNER'), ('COMMENTATOR', 'COMMENTATOR'), ('EDITOR', 'EDITOR')], max_length=20, verbose_name='Access type'),
        ),
        migrations.AlterField(
            model_name='file',
            name='place_id',
            field=models.CharField(choices=[('CM', 'Community'), ('MF', 'My Files'), ('BP', 'Best Practices')], max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='type_id',
            field=models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('Excel', 'Excel'), ('PDF', 'PDF')], max_length=10),
        ),
    ]
