# Generated by Django 4.0 on 2024-03-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0002_alter_file_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
