# Generated by Django 4.0 on 2024-03-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0002_charts_comments_alter_access_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangedate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_date', to='app_database.userproxy'),
        ),
    ]
