# Generated by Django 4.0 on 2024-03-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0005_alter_passwordchangedate_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangedate',
            name='change_type',
            field=models.CharField(choices=[('created', 'Пароль создан'), ('changed', 'Пароль изменен')], default='created', editable=False, max_length=10),
        ),
    ]
