# Generated by Django 4.0 on 2024-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0006_alter_passwordchangedate_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='place_id',
            field=models.CharField(choices=[('CM', 'Community'), ('MF', 'My Files'), ('BP', 'Best Practices')], default='MF', max_length=10),
        ),
    ]
